export default [
  {word: "Algorithm", hint:"Rules to be followed while solving a problem"},
  {word: "Template", hint:"Something that establishes or serves as a pattern"},
  {word: "Ethics", hint:"Deciding what is morally right and wrong in life"},
  {word: "Teamwork", hint:"Working together cooperatively, pulling together, turning a group into a team"},
  {word: "Perseverance", hint:"Sticking at it, hanging in there; important for programming"},
  {word: "Resilience", hint:"Bouncing back, (from failure), important for programming especially when dealing with mistakes in programming"},
  {word: "Google", hint:"When Stuck in something you _____ it"},
  {word: "Procedure", hint:"like a function, that can be used again and again but doesn't return a value."},
  {word: "Sophomore", hint:"2nd year student"},
  {word: "Peace", hint:"Being calm"},
  {word: "Illumination", hint:"Lights on"},
  {word: "Python", hint:"Snake/Prog Language"},
  {word: "Youtube", hint:"The World of video"},
  {word: "Histogram", hint:"A graph"},
  {word: "Chthonic", hint:"Of or relating to the underworld"},
  {word: "Squush", hint:"To crush something"},
  {word: "Database", hint:"Collection of info organized in such a way that a computer program can quickly select desired pieces of data"},
  {word: "Vowels", hint:"a e i o u"},
  {word: "Adversary", hint:"Someone who offers opposition"},
  {word: "Apprehensive", hint:"in fear or dread of possible evil or harm"},
  {word: "Aptitude", hint:"Inherent ability"},
  {word: "Barricade", hint:"Block off with barriers"},
  {word: "Commotion", hint:"Confused movement"},
  {word: "Olympics", hint:"5 circles"},
  {word: "Cricket", hint:"Bat and Ball"},
  {word: "India", hint:"Bharat"},
  {word: "Debris", hint:"Remains of somehting that has been destroyed"},
  {word: "Fragrance", hint:"Distinct order that is pleasant"},
  {word: "Hasten", hint:"Speeding up the process"},
  {word: "Antartica", hint:"Coldest Continent"},
  {word: "Engineering", hint:"Branch of science and technology concerned with the design, building, and use of engines, machines, and structures."},
  {word: "Potential", hint:"Existing in possibility"},
  {word: "Infinitesimal", hint:"Immeasurable small"},
  {word: "Paradox", hint:"Something that contradicts itself"},
  {word: "Hospital", hint:"___ Provides medical treatment"},
  {word: "Russia", hint:"Largest country in the world"},
  {word: "Football", hint:"Soccer"},
  {word: "Research", hint:"Investigate"},
  {word: "Instagram", hint:"A social media"},
];
